### ISSUE TITLE
Markdown viewer font size 

### ISSUE THREAD

**Issue by KennethNye** [cweijan/vscode-office#322]
I could not find where to change the markdown viewer's font size. The default size is too small for reading. Could you tell me how to change the font size without changing the editor size as well?

**Comment by Weijiang-Xiong** [comment]
same here, is there a way now?

**Comment by ZashIn** [comment]
A temporary workaround would be to edit the CSS definition of the extension directly, which you need to redo on reinstall / update:
In `.vscode/extensions/cweijan.vscode-office-3.5.4/resource/vditor/css/base.css`:
replace
```css
.vditor-reset {
    font-size: var(--vscode-editor-font-size);
}
```
with something like
```css
.vditor-reset {
    font-size: calc(var(--vscode-editor-font-size) + 2px);
}
```
To add `2px` to the default vscode font size, or simply `font-size: 16px` for a fixed value.
