### ISSUE TITLE
[BUG]不能隐藏样式标记

### ISSUE THREAD

**Issue by epodak** [cweijan/vscode-office#402]
- OS:win11
- Extension Version:3.51

```css
/* 隐藏左侧的样式标记 */
.vditor-wysiwyg .vditor-wysiwyg__block:before,
.vditor-ir .vditor-ir__node:before,
.vditor-sv .vditor-sv__marker {
    display: none !important;
}

/* 移除左侧标记后调整内容边距 */
.vditor-wysiwyg .vditor-wysiwyg__block,
.vditor-ir .vditor-ir__node,
.vditor-sv .vditor-sv__marker--heading {
    padding-left: 0 !important;
    margin-left: 0 !important;
}
```
这个能隐藏掉 front-matter 和 code 标记,但是 Heading 仍然存在.

我尝试更复杂的,也没解决
```css
/* 隐藏左侧的样式标记 */
.vditor-wysiwyg .vditor-wysiwyg__block:before,
.vditor-ir .vditor-ir__node:before,
.vditor-sv .vditor-sv__marker,
.vditor-sv [data-type="heading-marker"],
.vditor-sv [data-type="heading1-marker"],
.vditor-sv [data-type="heading2-marker"],
.vditor-sv [data-type="heading3-marker"],
.vditor-sv [data-type="heading4-marker"],
.vditor-sv [data-type="heading5-marker"],
.vditor-sv [data-type="heading6-marker"],
.vditor-sv .vditor-sv__marker--h1,
.vditor-sv .vditor-sv__marker--h2,
.vditor-sv .vditor-sv__marker--h3,
.vditor-sv .vditor-sv__marker--h4,
.vditor-sv .vditor-sv__marker--h5,
.vditor-sv .vditor-sv__marker--h6,
.vditor-preview .vditor-reset h1:before,
.vditor-preview .vditor-reset h2:before,
.vditor-preview .vditor-reset h3:before,
.vditor-preview .vditor-reset h4:before,
.vditor-preview .vditor-reset h5:before,
.vditor-preview .vditor-reset h6:before {
    display: none !important;
}

/* 移除左侧标记后调整内容边距 */
.vditor-wysiwyg .vditor-wysiwyg__block,
.vditor-ir .vditor-ir__node,
.vditor-sv .vditor-sv__marker--heading,
.vditor-sv [data-type="heading-marker"],
.vditor-sv [data-type="heading1-marker"],
.vditor-sv [data-type="heading2-marker"],
.vditor-sv [data-type="heading3-marker"],
.vditor-sv [data-type="heading4-marker"],
.vditor-sv [data-type="heading5-marker"],
.vditor-sv [data-type="heading6-marker"],
.vditor-preview .vditor-reset h1,
.vditor-preview .vditor-reset h2,
.vditor-preview .vditor-reset h3,
.vditor-preview .vditor-reset h4,
.vditor-preview .vditor-reset h5,
.vditor-preview .vditor-reset h6 {
    padding-left: 0 !important;
    margin-left: 0 !important;
}
```

**Comment by epodak** [comment]
```css
/* 隐藏左侧的样式标记 - 更新版本 */
.vditor-wysiwyg > .vditor-reset > h1:before,
.vditor-wysiwyg > .vditor-reset > h2:before,
.vditor-wysiwyg > .vditor-reset > h3:before,
.vditor-wysiwyg > .vditor-reset > h4:before,
.vditor-wysiwyg > .vditor-reset > h5:before,
.vditor-wysiwyg > .vditor-reset > h6:before,
.vditor-wysiwyg div.vditor-wysiwyg__block:before,
.vditor-wysiwyg div[data-type="link-ref-defs-block"]:before,
.vditor-wysiwyg div[data-type="footnotes-block"]:before,
.vditor-wysiwyg .vditor-toc:before,
.vditor-wysiwyg div.vditor-wysiwyg__block[data-type="yaml-front-matter"]:before,
.vditor-wysiwyg div.vditor-wysiwyg__block[data-type="math-block"]:before,
.vditor-ir .vditor-ir__node:before,
.vditor-sv .vditor-sv__marker {
    display: none !important;
    content: none !important;
}

/* 调整内容边距，确保隐藏标记后文本不会显得过于靠左 */
.vditor-wysiwyg > .vditor-reset > h1,
.vditor-wysiwyg > .vditor-reset > h2,
.vditor-wysiwyg > .vditor-reset > h3,
.vditor-wysiwyg > .vditor-reset > h4,
.vditor-wysiwyg > .vditor-reset > h5,
.vditor-wysiwyg > .vditor-reset > h6,
.vditor-wysiwyg div.vditor-wysiwyg__block,
.vditor-wysiwyg div[data-type="link-ref-defs-block"],
.vditor-wysiwyg div[data-type="footnotes-block"],
.vditor-wysiwyg .vditor-toc {
    margin-left: 0 !important;
    padding-left: 0 !important;
}
```
这样解决
